/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface CardEntry {
    cardId: number;
    count: number;
    deckId: number;
}

export interface CardPrice {
    cardId: number;
    formatId: number;
    priceInUsd: number;
}

export interface Card {
    displayName: string;
    id: Generated<number>;
    imageUrl: string;
    scryfallUrl: string;
}

export interface Deck {
    createdAt: Generated<Date>;
    displayName: string;
    formatId: number;
    id: Generated<number>;
    ownerId: number;
    updatedAt: Generated<Date>;
}

export interface Format {
    createdAt: Generated<Date>;
    displayName: string | null;
    id: Generated<number>;
}

export interface Session {
    data: string | null;
    expires: number;
    sessionId: string;
}

export interface User {
    createdAt: Generated<Date>;
    displayName: string;
    googleUserId: string;
    id: Generated<number>;
}

export interface DB {
    cardEntries: CardEntry;
    cardPrices: CardPrice;
    cards: Card;
    decks: Deck;
    formats: Format;
    sessions: Session;
    users: User;
}
